### ISSUE TITLE
create new OG_SABR_small.zip

### ISSUE THREAD

**Issue by jgheerardyn** [jgheerardyn/yields#125]
When trying to zip the output of running OGSABRTest to create a zip file to populate Redis, I get errors below:

Sending data from /werk/data/og_sabr_small.zip to http://localhost:8090 with token yields
data folder: /var/folders/qk/wcmdwkp53wxdn0r_6l6lvq380000gp/T/yields_data8589302107922863052
Exception in thread "main" java.lang.IllegalStateException: java.nio.file.NotDirectoryException: /var/folders/qk/wcmdwkp53wxdn0r_6l6lvq380000gp/T/yields_data8589302107922863052/__MACOSX/og_sabr_small/._.DS_Store
	at io.yields.testpad.rest.api.ExplorerResultHandler.list(ExplorerResultHandler.java:563)
	at io.yields.testpad.rest.api.ExplorerResultHandler.lambda$null$16(ExplorerResultHandler.java:527)
	at io.yields.testpad.rest.api.ExplorerResultHandler$$Lambda$5/204349222.accept(Unknown Source)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at io.yields.testpad.rest.api.ExplorerResultHandler.lambda$null$17(ExplorerResultHandler.java:525)
	at io.yields.testpad.rest.api.ExplorerResultHandler$$Lambda$4/110718392.accept(Unknown Source)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at io.yields.testpad.rest.api.ExplorerResultHandler.lambda$main$18(ExplorerResultHandler.java:525)
	at io.yields.testpad.rest.api.ExplorerResultHandler$$Lambda$3/250075633.accept(Unknown Source)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at io.yields.testpad.rest.api.ExplorerResultHandler.main(ExplorerResultHandler.java:525)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

when running ExporerResultHandler. 

Please replace zip file (with small data set) here:
https://github.com/jgheerardyn/yields/blob/master/foundations/src/test/resources/og_sabr_small.zip

**Comment by rombautt** [comment]
You don't need to create a new zip, it was just when sending that the data got formatted to a string.
If you do want to create a new zip, use the commandline zip command, the macos compressor adds some hidden folders.
