### ISSUE TITLE
Tests fail on Windows

### ISSUE THREAD

**Issue by AdamNowaczyk** [jgheerardyn/yields#128]
I'm getting this error while trying to build and run tests with maven. This looks like an error in foundation project:

```java
io.yields.math.framework.data.DataProvidersTest  Time elapsed: 0.672 sec  <<< ERROR!
java.lang.IllegalStateException: Failed to dispose file .\e68252d3-fb9e-4053-8376-d7cec9ce9177.dat
	at io.yields.math.framework.memory.OffHeapStore.dispose(OffHeapStore.java:87)
	at io.yields.math.framework.ExplorerBatch.dispose(ExplorerBatch.java:258)
	at io.yields.math.framework.Explorer$$Lambda$135/1328718765.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at io.yields.math.framework.Explorer.dispose(Explorer.java:180)
	at io.yields.math.framework.junit.ExploreRunner.runChild(ExploreRunner.java:278)
	at io.yields.math.framework.junit.ExploreRunner.runChild(ExploreRunner.java:60)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.io.IOException: Unable to delete file: .\e68252d3-fb9e-4053-8376-d7cec9ce9177.dat
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2279)
	at io.yields.math.framework.memory.OffHeapStore.dispose(OffHeapStore.java:85)
	at io.yields.math.framework.ExplorerBatch.dispose(ExplorerBatch.java:258)
	at io.yields.math.framework.Explorer$$Lambda$135/1328718765.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at io.yields.math.framework.Explorer.dispose(Explorer.java:180)
	at io.yields.math.framework.junit.ExploreRunner.runChild(ExploreRunner.java:278)
	at io.yields.math.framework.junit.ExploreRunner.runChild(ExploreRunner.java:60)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

**Comment by rombautt** [comment]
@AdamNowaczyk should be fixed, could you retry please?

**Comment by AdamNowaczyk** [comment]
@rombautt yes, I confirm this is not happening anymore on the windows build.

**Comment by jgheerardyn** [comment]
@rombautt Dmitry has again failing tests on Windows (in master). Example 
io.yields.math.framework.kpi.ScoreTest
error is the cause is java.io.IOException: Unable to delete file: ...yields\foundations\target\8e359f2c-86eb-467c-b107-0bc990af2ff7.dat

Can you have a look?

**Comment by jgheerardyn** [comment]
When running on Jenkins we have similar issue:

[main] ERROR io.yields.math.framework.memory.OffHeapStore - Failed to dispose file .\54bc84c5-f093-4132-8920-646e9e9a237a.dat
java.io.IOException: Unable to delete file: .\54bc84c5-f093-4132-8920-646e9e9a237a.dat
 at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2279)
 at io.yields.math.framework.memory.OffHeapStore.dispose(OffHeapStore.java:94)
 at io.yields.math.framework.ExplorerBatch.dispose(ExplorerBatch.java:253)
 at io.yields.math.framework.Explorer$$Lambda$209/44559647.accept(Unknown Source)
 at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
 at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
 at io.yields.math.framework.Explorer.dispose(Explorer.java:197)
 at io.yields.math.framework.junit.ExploreRunner.runChild(ExploreRunner.java:278)
 at io.yields.math.framework.junit.ExploreRunner.runChild(ExploreRunner.java:60)
 at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
 at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
 at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
 at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
 at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
 at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
 at org.junit.runners.Suite.runChild(Suite.java:127)
 at org.junit.runners.Suite.runChild(Suite.java:26)
 at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
 at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
 at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
 at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
 at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
 at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
 at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
 at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
 at org.junit.runner.JUnitCore.run(JUnitCore.java:128)
 at io.yields.testpad.junit.TestDefinitionRunner.main(TestDefinitionRunner.java:277)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 at java.lang.reflect.Method.invoke(Unknown Source)
 at com.simontuffs.onejar.Boot.run(Boot.java:306)
 at com.simontuffs.onejar.Boot.main(Boot.java:159)
