### ISSUE TITLE
error in KPI report publisher

### ISSUE THREAD

**Issue by jgheerardyn** [jgheerardyn/yields#147]
when driving tests from TestPad, I often get errors like this one:
[YIELDS_TEST_PAD] POST Records_0_100[testpad_build/15092015141848/test/test_15092015141848] completed in 22 ms
Recording test results
[YIELDS] Scanning for KPI Scores in path /var/folders/qk/wcmdwkp53wxdn0r_6l6lvq380000gp/T/yields (trendSize = 10, detailSize = 5)
ERROR: Build step failed with exception
java.lang.ArrayIndexOutOfBoundsException: 0
	at java.util.Arrays$ArrayList.get(Arrays.java:3841)
	at io.yields.plugins.kpi.KPIReportPublisher.perform(KPIReportPublisher.java:294)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:761)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:721)
	at hudson.model.Build$BuildExecution.post2(Build.java:183)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:670)
	at hudson.model.Run.execute(Run.java:1775)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)
Build step 'Publish Yields KPI Reports' marked build as failure
Finished: FAILURE

**Comment by rombautt** [comment]
@jgheerardyn this looks like the post build plugin, in combination with the standalone runner?

**Comment by jgheerardyn** [comment]
this is the post-build config i am using. Please let me know if wrong...

![image](https://cloud.githubusercontent.com/assets/6535557/9883475/94e359a2-5bda-11e5-9c07-2c6efeabac53.png)

**Comment by rombautt** [comment]
@jgheerardyn well, it's one or the other. The standalone runner run.sh now has a -sendResult option hardcoded in the script, this already sends all results to testpad.

If you really want the post build plugin, that's possible, though I don't think you can use it with the -sendResult option, as it changes the result folder (and the post plugin has no means of knowing this).
